### ISSUE TITLE
Update reference to depreciated elm package in /json-to-elm

### ISSUE THREAD

**Issue by pete-a** [NoRedInk/noredink.github.io#4]
I stumbled over your great tool to convert JSON into Elm data types (http://noredink.github.io/json-to-elm/). Part of the generated Elm code has this line:
```
-- elm-package install --yes circuithub/elm-json-extra
```
This package doesn't work with Elm 0.18 as it's depreciated, with the package now moved to `elm-community/json-extra`. It would be great to update this in the generated code comment.

I would submit a pull request, however it seems only the compiled JS in in this repo (it would be awesome if it could also be open sourced).
Thanks!

**Comment by eeue56** [comment]
It is open source. It's at https://github.com/eeue56/json-to-elm

**Comment by pete-a** [comment]
Pull request created: https://github.com/eeue56/json-to-elm/pull/23
